# Generated by Django 4.1.3 on 2022-11-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_ingredients_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="recipes.ingredient"),
        ),
    ]
