# Generated by Django 4.1.3 on 2022-11-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_ingredient_amount_remove_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="amount",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients", to="recipes.ingredient"
            ),
        ),
    ]
